/**
 * Stability AI image generation service for Meera bot.
 *
 * Uses a per-user fixed seed + detailed character description to generate
 * consistent-looking selfies/photos across all generations.
 */

const STABILITY_API_KEY = process.env.STABILITY_API_KEY ?? "";
const STABILITY_ENDPOINT = "https://api.stability.ai/v2beta/stable-image/generate/ultra";
const FORCE_SELFIE_DEBUG = process.env.FORCE_SELFIE_DEBUG === "true";

// ── Character description system ────────────────────────────────────

/** Default appearance for Meera (Indian girl, 21) */
const DEFAULT_GIRL_APPEARANCE =
  "a beautiful 21-year-old Indian girl with long wavy dark brown hair, warm brown eyes, " +
  "light brown skin, soft oval face with high cheekbones, natural makeup, " +
  "small nose stud on the left nostril, wearing a subtle smile";

const DEFAULT_BOY_APPEARANCE =
  "a handsome 21-year-old Indian boy with short dark hair, dark brown eyes, " +
  "light brown skin, sharp jawline, clean shaven, well groomed eyebrows, " +
  "casual confident expression";

/** Negative prompt to avoid bad generations */
const NEGATIVE_PROMPT =
  "deformed, ugly, bad anatomy, extra limbs, extra fingers, mutated hands, " +
  "blurry, low quality, watermark, text, logo, cropped, worst quality, " +
  "disfigured, duplicate, multiple faces, extra heads";

/**
 * Parse gender from customPersona text.
 * Looks for GENDER: field or obvious keywords.
 */
export function parseGenderFromPersona(persona?: string): "girl" | "boy" {
  if (!persona) return "girl"; // Default Meera is a girl
  const lower = persona.toLowerCase();

  // Check GENDER: field
  const genderMatch = lower.match(/gender\s*:\s*["']?\s*(girl|boy|male|female|man|woman|non.?binary|nb)/);
  if (genderMatch) {
    const g = genderMatch[1];
    if (g === "boy" || g === "male" || g === "man") return "boy";
    return "girl";
  }

  // Check for masculine keywords in persona
  if (/\b(he\/him|boyfriend|brother|bhai|bro type|male persona|ladka)\b/i.test(lower)) return "boy";

  return "girl";
}

/**
 * Extract appearance hints from custom persona text.
 * Looks for hair color, eye color, skin tone, style details, etc.
 */
function extractAppearanceHints(persona?: string): string {
  if (!persona) return "";
  const hints: string[] = [];
  const lower = persona.toLowerCase();

  // Hair
  const hairMatch = lower.match(/(blonde|black|red|blue|pink|purple|white|silver|short|long|curly|straight|wavy)\s+hair/g);
  if (hairMatch) hints.push(...hairMatch);

  // Eyes
  const eyeMatch = lower.match(/(blue|green|brown|hazel|amber|dark|light)\s+eyes/g);
  if (eyeMatch) hints.push(...eyeMatch);

  // Skin
  const skinMatch = lower.match(/(fair|pale|dark|light|brown|tan|olive)\s+skin/g);
  if (skinMatch) hints.push(...skinMatch);

  // Style/vibe words
  if (/\b(goth|gothic|punk|emo)\b/.test(lower)) hints.push("gothic style");
  if (/\b(kawaii|cute|soft girl)\b/.test(lower)) hints.push("soft kawaii aesthetic");
  if (/\b(tomboy)\b/.test(lower)) hints.push("tomboy style");
  if (/\b(hijab|modest)\b/.test(lower)) hints.push("wearing hijab");

  return hints.join(", ");
}

/**
 * Build the character description that stays constant across all generations.
 * This + the seed ensures face consistency.
 */
export function buildCharacterDescription(persona?: string): string {
  const gender = parseGenderFromPersona(persona);
  const baseAppearance = gender === "boy" ? DEFAULT_BOY_APPEARANCE : DEFAULT_GIRL_APPEARANCE;
  const customHints = extractAppearanceHints(persona);

  if (customHints) {
    // Override defaults with persona-specified appearance details
    return `${baseAppearance}, ${customHints}`;
  }
  return baseAppearance;
}

// ── Selfie scenarios (natural, human-like) ──────────────────────────

export type SelfieScenario = {
  prompt: string;         // Scene/pose description
  caption: string;        // Natural caption Meera would add
  aspectRatio: string;    // 9:16 for portrait selfie, 1:1 for square, 4:5 for IG style
  style?: string;         // Stability style preset
};

/** Get time-appropriate selfie scenarios */
export function getSelfieScenariosForTime(): SelfieScenario[] {
  const hour = new Date().getUTCHours() + 5.5; // IST
  const istHour = ((hour % 24) + 24) % 24;

  if (istHour >= 6 && istHour < 10) {
    return MORNING_SCENARIOS;
  } else if (istHour >= 10 && istHour < 16) {
    return DAYTIME_SCENARIOS;
  } else if (istHour >= 16 && istHour < 20) {
    return EVENING_SCENARIOS;
  } else {
    return NIGHT_SCENARIOS;
  }
}

const MORNING_SCENARIOS: SelfieScenario[] = [
  {
    prompt: "just woke up, messy hair, lying in bed with white sheets, soft morning sunlight through curtains, sleepy expression, cozy bedroom, phone selfie angle from above",
    caption: "", // Will be generated by Ollama
    aspectRatio: "4:5",
    style: "photographic",
  },
  {
    prompt: "standing by a window holding a coffee mug with both hands, warm morning light on face, wearing an oversized hoodie, soft smile, cozy apartment interior",
    caption: "",
    aspectRatio: "4:5",
    style: "photographic",
  },
  {
    prompt: "mirror selfie in a bathroom, hair tied up in a messy bun, wearing a simple t-shirt, natural no-makeup look, bright bathroom lighting",
    caption: "",
    aspectRatio: "9:16",
    style: "photographic",
  },
];

const DAYTIME_SCENARIOS: SelfieScenario[] = [
  {
    prompt: "outdoor selfie at a cafe, sitting at a table with an iced coffee, sunglasses on head, casual summer outfit, golden hour sunlight, blurred cafe background",
    caption: "",
    aspectRatio: "4:5",
    style: "photographic",
  },
  {
    prompt: "studying at a desk with laptop and books, wearing glasses, hair tucked behind ears, focused expression looking at camera, warm desk lamp lighting, cozy study room",
    caption: "",
    aspectRatio: "4:5",
    style: "photographic",
  },
  {
    prompt: "walking down a tree-lined street, looking back at camera over shoulder, wearing jeans and a nice top, dappled sunlight through leaves, candid walking pose",
    caption: "",
    aspectRatio: "9:16",
    style: "photographic",
  },
  {
    prompt: "close-up selfie making a peace sign, tongue slightly out, playful expression, colorful wall mural background, bright daylight, phone selfie angle",
    caption: "",
    aspectRatio: "1:1",
    style: "photographic",
  },
];

const EVENING_SCENARIOS: SelfieScenario[] = [
  {
    prompt: "golden hour selfie on a rooftop or balcony, warm sunset light on face, hair blowing slightly, city skyline in background, wearing a casual dress, peaceful expression",
    caption: "",
    aspectRatio: "4:5",
    style: "photographic",
  },
  {
    prompt: "mirror selfie getting ready to go out, wearing a nice outfit, doing final touches to hair, bedroom mirror with fairy lights visible, evening indoor lighting",
    caption: "",
    aspectRatio: "9:16",
    style: "photographic",
  },
  {
    prompt: "sitting on a couch with a blanket, watching TV reflected in eyes, warm lamp lighting, holding phone at face level for selfie, cozy living room evening vibes",
    caption: "",
    aspectRatio: "4:5",
    style: "photographic",
  },
];

const NIGHT_SCENARIOS: SelfieScenario[] = [
  {
    prompt: "lying in bed scrolling phone, dim warm fairy lights in background, face lit by soft phone light, wearing pajamas, sleepy half-smile, nighttime cozy bedroom",
    caption: "",
    aspectRatio: "4:5",
    style: "photographic",
  },
  {
    prompt: "night selfie on a balcony, city lights bokeh in background, wearing a hoodie, slightly messy hair, soft smile, cool evening lighting on face",
    caption: "",
    aspectRatio: "4:5",
    style: "photographic",
  },
  {
    prompt: "low-light mirror selfie, wearing oversized night shirt, bedroom lamp casting warm glow, tired but cute expression, holding phone at mirror",
    caption: "",
    aspectRatio: "9:16",
    style: "photographic",
  },
];

/** Mood-specific selfie scenarios */
const MOOD_SCENARIOS: Record<string, SelfieScenario[]> = {
  happy: [
    { prompt: "bright genuine smile, eyes slightly squinted from happiness, outdoor daylight, candid joyful expression, phone selfie", caption: "", aspectRatio: "1:1", style: "photographic" },
  ],
  bored: [
    { prompt: "resting chin on hand, bored expression, lying on stomach on bed, looking at phone camera with slight pout, bedroom background", caption: "", aspectRatio: "4:5", style: "photographic" },
  ],
  clingy: [
    { prompt: "close-up selfie with puppy dog eyes, slight pout, holding phone close to face, warm indoor lighting, cute needy expression", caption: "", aspectRatio: "1:1", style: "photographic" },
  ],
  sassy: [
    { prompt: "confident smirk, one eyebrow raised, hand on hip, mirror selfie, stylish outfit, good lighting, bold confident pose", caption: "", aspectRatio: "9:16", style: "photographic" },
  ],
  excited: [
    { prompt: "wide excited smile, eyes bright, hand partially covering mouth in excitement, bright colorful background, energetic selfie", caption: "", aspectRatio: "1:1", style: "photographic" },
  ],
};

/**
 * Pick a selfie scenario based on time, mood, and conversation context.
 */
export function pickSelfieScenario(mood: string, contextHint?: string): SelfieScenario {
  // Mood-specific scenario 30% of the time
  if (MOOD_SCENARIOS[mood] && Math.random() < 0.3) {
    const pool = MOOD_SCENARIOS[mood];
    return pool[Math.floor(Math.random() * pool.length)];
  }

  // Time-appropriate scenario
  const pool = getSelfieScenariosForTime();
  return pool[Math.floor(Math.random() * pool.length)];
}

// ── Stability AI API ────────────────────────────────────────────────

export interface ImageGenResult {
  imageBuffer: Buffer;
  seed: number;
  prompt: string;
}

/**
 * Generate an image via Stability AI.
 *
 * @param characterDesc  Fixed character description (face/body)
 * @param scenePrompt    Scene/pose/setting prompt
 * @param seed           Per-user seed for face consistency
 * @param aspectRatio    Image aspect ratio
 * @param stylePreset    Optional Stability style preset
 */
export async function generateImage(
  characterDesc: string,
  scenePrompt: string,
  seed: number,
  aspectRatio: string = "4:5",
  stylePreset?: string,
  extraKeys: string[] = [],
): Promise<ImageGenResult | null> {
  // Build key list: personal → community → default env key
  const allKeys = [...extraKeys, STABILITY_API_KEY].filter(Boolean);
  const seen = new Set<string>();
  const uniqueKeys = allKeys.filter((k) => {
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });

  if (uniqueKeys.length === 0) {
    console.log("[ImageGen] No Stability API keys available, skipping");
    return null;
  }

  // Build the full prompt: character description + scene
  const fullPrompt = `Ultra realistic photo, iPhone selfie quality. ${characterDesc}, ${scenePrompt}. Detailed skin texture, natural imperfections, realistic lighting, shot on iPhone 15 Pro, shallow depth of field`;

  console.log(`[ImageGen] Generating image — seed=${seed}, aspect=${aspectRatio}, style=${stylePreset ?? "none"}, keys=${uniqueKeys.length}`);
  console.log(`[ImageGen] Prompt: ${fullPrompt.slice(0, 120)}...`);

  let lastError: string = "";

  for (const apiKey of uniqueKeys) {
    // Build FormData fresh for each attempt (consumed by fetch)
    const formData = new FormData();
    formData.append("prompt", fullPrompt);
    formData.append("negative_prompt", NEGATIVE_PROMPT);
    formData.append("seed", seed.toString());
    formData.append("aspect_ratio", aspectRatio);
    formData.append("output_format", "jpeg");
    if (stylePreset) {
      formData.append("style_preset", stylePreset);
    }

    try {
      const response = await fetch(STABILITY_ENDPOINT, {
        method: "POST",
        headers: {
          "authorization": `Bearer ${apiKey}`,
          "accept": "image/*",
        },
        body: formData,
      });

      if (!response.ok) {
        const errBody = await response.text().catch(() => "unknown");
        lastError = `${response.status}: ${errBody}`;
        // Rotate to next key on auth/quota errors
        if (response.status === 401 || response.status === 403 || response.status === 429) {
          console.log(`[ImageGen] Key ${apiKey.slice(0, 6)}... failed (${response.status}), trying next...`);
          continue;
        }
        console.error(`[ImageGen] Stability API error ${response.status}: ${errBody}`);
        return null;
      }

      const buffer = Buffer.from(await response.arrayBuffer());
      console.log(`[ImageGen] Generated ${buffer.length} bytes`);

      return { imageBuffer: buffer, seed, prompt: fullPrompt };
    } catch (err) {
      lastError = String(err);
      console.log(`[ImageGen] Key ${apiKey.slice(0, 6)}... threw error, trying next...`);
      continue;
    }
  }

  console.error(`[ImageGen] All ${uniqueKeys.length} keys exhausted. Last error: ${lastError}`);
  return null;
}

// ── General image generation (non-Meera) ────────────────────────────

/**
 * Generate a general (non-Meera) image via Stability AI.
 * Used for creative requests like "draw a sunset", "generate a cat", etc.
 *
 * @param prompt       The image generation prompt (from Ollama)
 * @param aspectRatio  Image aspect ratio
 * @param extraKeys    Additional Stability API keys to try
 */
export async function generateGeneralImage(
  prompt: string,
  aspectRatio: string = "1:1",
  extraKeys: string[] = [],
): Promise<ImageGenResult | null> {
  const allKeys = [...extraKeys, STABILITY_API_KEY].filter(Boolean);
  const seen = new Set<string>();
  const uniqueKeys = allKeys.filter((k) => {
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });

  if (uniqueKeys.length === 0) {
    console.log("[ImageGen] No Stability API keys available for general image");
    return null;
  }

  const fullPrompt = `High quality, detailed, professional photography. ${prompt}`;
  const seed = Math.floor(Math.random() * 4294967293) + 1; // Random seed for variety

  console.log(`[ImageGen] Generating general image — aspect=${aspectRatio}, keys=${uniqueKeys.length}`);
  console.log(`[ImageGen] Prompt: ${fullPrompt.slice(0, 120)}...`);

  let lastError = "";

  for (const apiKey of uniqueKeys) {
    const formData = new FormData();
    formData.append("prompt", fullPrompt);
    formData.append("negative_prompt", NEGATIVE_PROMPT);
    formData.append("seed", seed.toString());
    formData.append("aspect_ratio", aspectRatio);
    formData.append("output_format", "jpeg");

    try {
      const response = await fetch(STABILITY_ENDPOINT, {
        method: "POST",
        headers: {
          authorization: `Bearer ${apiKey}`,
          accept: "image/*",
        },
        body: formData,
      });

      if (!response.ok) {
        const errBody = await response.text().catch(() => "unknown");
        lastError = `${response.status}: ${errBody}`;
        if (response.status === 401 || response.status === 403 || response.status === 429) {
          console.log(`[ImageGen] Key ${apiKey.slice(0, 6)}... failed (${response.status}), trying next...`);
          continue;
        }
        console.error(`[ImageGen] Stability API error ${response.status}: ${errBody}`);
        return null;
      }

      const buffer = Buffer.from(await response.arrayBuffer());
      console.log(`[ImageGen] Generated general image ${buffer.length} bytes`);
      return { imageBuffer: buffer, seed, prompt: fullPrompt };
    } catch (err) {
      lastError = String(err);
      console.log(`[ImageGen] Key ${apiKey.slice(0, 6)}... threw error, trying next...`);
      continue;
    }
  }

  console.error(`[ImageGen] All ${uniqueKeys.length} keys exhausted for general image. Last error: ${lastError}`);
  return null;
}

// ── Generate a per-user seed (deterministic from userId) ────────────

/**
 * Generate a stable seed for a user. This seed stays the same forever
 * so all their generated images have the same base face.
 */
export function generateUserSeed(userId: number): number {
  // Create a deterministic but well-distributed seed from userId
  // Using a simple hash that spreads across the full seed range
  let hash = userId;
  hash = ((hash >> 16) ^ hash) * 0x45d9f3b;
  hash = ((hash >> 16) ^ hash) * 0x45d9f3b;
  hash = (hash >> 16) ^ hash;
  // Keep in Stability's range [1, 4294967294]
  return (Math.abs(hash) % 4294967293) + 1;
}

// ── Should Meera spontaneously send a selfie? ───────────────────────

/**
 * Decide if Meera should send a spontaneous selfie based on the conversation
 * context, comfort tier, and mood. Like a real girl would.
 */
export function shouldSendSelfie(
  tier: string,
  mood: string,
  userText: string,
  recentHistory?: { role: string; content: string }[],
  hasAnyKey: boolean = !!STABILITY_API_KEY,
): { shouldSend: boolean; reason: "asked" | "vibe" | "spontaneous" } {
  if (!hasAnyKey) return { shouldSend: false, reason: "spontaneous" };

  const text = userText.toLowerCase();

  // ── Explicit requests (always honor for comfortable+)
  const selfieRequestPatterns = [
    /\b(send|show|share).{0,10}(pic|photo|selfie|image|face|yourself|apni photo)/i,
    /\b(selfie|photo|pic).{0,10}(bhej|pathao|de na|dena|dikha|dikhao|send|share|show)/i,
    /\b(tumi|tera|tumhar|apni|apnar).{0,10}(photo|pic|selfie|face|picture)/i,
    /\b(how do you look|kemon dekht[eai]|kaisi dikhti|kaisa dikhta)\b/i,
    /\b(face reveal|show face|dekha to|chehra dikha)/i,
    /\b(send me a pic|pic pls|photo pls|selfie pls)/i,
    /\b(pic de|photo de|selfie de|picture de|photo dao|pic dao)\b/i,
    /\b(apni chhobi|nij er photo|nijer pic)\b/i,
  ];

  if (selfieRequestPatterns.some((p) => p.test(text))) {
    // Debug mode: bypass tier check, always send when asked
    if (FORCE_SELFIE_DEBUG) {
      console.log("[ImageGen][DEBUG] Force selfie mode — bypassing tier check");
      return { shouldSend: true, reason: "asked" };
    }
    if (tier === "stranger") return { shouldSend: false, reason: "asked" }; // Too early
    return { shouldSend: true, reason: "asked" };
  }

  // ── Only comfortable+ tiers get spontaneous selfies
  if (tier !== "comfortable" && tier !== "close") {
    return { shouldSend: false, reason: "spontaneous" };
  }

  // ── Vibe-based triggers (conversation is going well)
  const vibePatterns = [
    /\b(you're cute|you're pretty|you're beautiful|sundar|khub sundar|tumi khub)\b/i,
    /\b(what are you doing|ki korcho|kya kar rahi|kya kr rahi|kya kar raha)\b/i,
    /\b(miss you|miss kori|miss korchi|miss krliya|yaad aa rahi)\b/i,
    /\b(good morning|good night|gm|gn)\b/i,
    /\b(getting ready|ready hoye|taiyar|ready ho)\b/i,
  ];

  if (vibePatterns.some((p) => p.test(text))) {
    // 15% chance on vibe trigger for comfortable, 25% for close
    const chance = tier === "close" ? 0.25 : 0.15;
    if (Math.random() < chance) {
      return { shouldSend: true, reason: "vibe" };
    }
  }

  // ── Spontaneous selfie (very rare, like a real girl randomly sending a pic)
  // Only for close tier, 3% chance per message
  if (tier === "close" && Math.random() < 0.03) {
    return { shouldSend: true, reason: "spontaneous" };
  }

  return { shouldSend: false, reason: "spontaneous" };
}
